common: &common
    adapter: mysql2
    host: localhost
    encoding: utf8
    pool: 25

production: &prod
    <<: *common
    username: root
    password: 3DvErBUC
    database: shooting_production
    host: 173.246.41.219

staging: &stag
    <<: *common
    username: root
    password: 3DvErBUC
    database: shooting_dev
    host: 173.246.41.219

development: &dev
    <<: *common
    username: root
    password: 3DvErBUC
    database: shooting_dev

test:
    <<: *common
    username: root
    password: 3DvErBUC
    database: shooting_test
